version: "3.3"

networks:
  default:
    external:
      name: ${APP_NAME}

services:

  backup-x:
    image: registry.cn-hangzhou.aliyuncs.com/huangyalong/jeessy_backup-x:v2.8.3
    container_name: ${APP_NAME}-backup
    ports:
      - "${BACKUP_PORT}:9977"
    environment:
      - "TZ=Asia/Shanghai"
    volumes:
      - "$PWD/data:/app/backup-x-files"
    restart: unless-stopped
