version: "3.3"

networks:
  default:
    external:
      name: ${APP_NAME}

services:

  qdrant:
    image: registry.cn-hangzhou.aliyuncs.com/huangyalong/qdrant:v1.15.5
    container_name: ${APP_NAME}-qdrant
    privileged: true
    ports:
      - "${QDRANT_GRPC_PORT}:6334"
      - "${QDRANT_HTTP_PORT}:6333"
    environment:
      - "TZ=Asia/Shanghai"
    volumes:
      - "$PWD/snapshots:/qdrant/snapshots"
      - "$PWD/data:/qdrant/storage"
    restart: unless-stopped
