version: "3.3"

networks:
  default:
    external:
      name: qwerty

services:

  minio:
    image: registry.cn-hangzhou.aliyuncs.com/huang6349/backup-x:v2.8.3
    container_name: project-backup
    ports:
      - "3277:9977"
    environment:
      - "TZ=Asia/Shanghai"
    volumes:
      - "$PWD/data:/app/backup-x-files"
    restart: unless-stopped
