version: "3.3"

networks:
  default:
    external:
      name: ${APP_NAME}

services:

  minio:
    image: registry.cn-hangzhou.aliyuncs.com/huangyalong/bitnamilegacy_minio:2024.6.13
    container_name: ${APP_NAME}-minio
    ports:
      - "${MINIO_CONSOLE_PORT}:9001"
      - "${MINIO_API_PORT}:9000"
    environment:
      - "MINIO_DEFAULT_BUCKETS=${APP_NAME}"
      - "MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}"
      - "TZ=Asia/Shanghai"
    volumes:
      - "$PWD/data:/bitnami/minio/data"
    restart: unless-stopped
