spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://100.100.100.252:3242/project
  username: postgres
  password: pwd123456
  hikari:
    minimum-idle: 10
    connection-test-query: SELECT 1
    maximum-pool-size: 20
    idle-timeout: 30000
    max-lifetime: 60000
    auto-commit: true
    pool-name: PrimaryHikariCP
    connection-timeout: 10000

spring.flyway:
  baseline-on-migrate: true
  baseline-version: 0
  enabled: true
  clean-disabled: false

spring.redis:
  database: 0
  host: 100.100.100.252
  port: 3279
  password: pwd123456
  timeout: 10s
  lettuce:
    pool:
      min-idle: 0
      max-active: 10
      max-idle: 200
      max-wait: -1ms

easy-es:
  address: 100.100.100.252:3202
  username: elastic
  password: pwd123456
