spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3206/project?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  username: root
  password: pwd123456
  hikari:
    minimum-idle: 10
    connection-test-query: SELECT 1
    maximum-pool-size: 20
    idle-timeout: 30000
    max-lifetime: 60000
    auto-commit: true
    pool-name: PrimaryHikariCP
    connection-timeout: 10000

spring.redis:
  database: 0
  host: 127.0.0.1
  port: 3279
  password: pwd123456
  timeout: 10s
  lettuce:
    pool:
      max-active: 200
      max-idle: 20
      max-wait: 10s
      min-idle: 10
    shutdown-timeout: 3s

easy-es:
  address: 127.0.0.1:3202
  username: elastic
  password: pwd123456
