version: "3.3"

networks:
  default:
    external:
      name: qwerty

services:

  service:
    build: $PWD/.
    container_name: project-service
    ports:
      - "3288:8088"
      - "3285:8085"
    environment:
      - "WAIT_LOGGER_LEVEL=info"
      - "WAIT_HOSTS=project-pg:5432"
      - "WAIT_TIMEOUT=900"
      - "WAIT_SLEEP_INTERVAL=5"
      - "TZ=Asia/Shanghai"
    volumes:
      - "$PWD/log:/log"
    restart: unless-stopped
