version: "3.3"

networks:
  default:
    external:
      name: ${APP_NAME}

services:

  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/huangyalong/linuxserver_nginx:1.26.2-r0-ls294
    container_name: ${APP_NAME}-nginx
    ports:
      - "${NGINX_HTTPS_PORT}:443"
      - "${NGINX_HTTP_PORT}:80"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Asia/Shanghai"
    volumes:
      - "$PWD/stream.d:/etc/nginx/stream.d"
      - "$PWD/config:/config"
    restart: unless-stopped
